# Generated by Django 3.2.6 on 2021-08-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_spy_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spy',
            options={'permissions': (('can_see_hitmen', "Is able to see the hitman's list"),)},
        ),
    ]
