# Generated by Django 3.2.6 on 2021-08-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0002_auto_20210825_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager3', to='spy_app.teammanager'),
        ),
    ]
