# Generated by Django 3.2.6 on 2021-08-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0004_alter_teammembers_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hit',
            options={'permissions': (('can_create_hit', 'Is able to create a Hit'),)},
        ),
    ]
